### PR TITLE
WIP: Add travis (fix #15)

### LINKED ISSUE #15: Code quality and automated checks on commits/PRs
Maybe setup Travis for building the template and checking code quality (with http://baruch.ev-en.org/proj/chktex/ for example) could be a good idea to prevent regressions.

### PR DESCRIPTION
**Pull request by pierre-24**
[27 builds](https://travis-ci.org/pierre-24/latex-template/builds) were finally enough.

### CODE REVIEW

**Comment by Karnaj** [comment]
Great work. ^^ 

Why `colorlinks=true` ? Because of menukeys we should load hyperref without `colorlinks` option.

**Comment by AmarOk1412** [comment]
Btw, you can change the Makefile and add a `make install` now :)

**Comment by pierre-24** [comment]
> Why colorlinks=true ? Because of menukeys we should load hyperref without colorlinks option.

Rebase error, it is now fixed ;)

> Btw, you can change the Makefile and add a make install now :)

Indeed :)

**Comment by pierre-24** [comment]
Ok. That's finally it :)

**Pull request merged**
