### PR TITLE
We can copy code without the line numbers

### PR DESCRIPTION
**Pull request by Situphen**
Related to [this topic](https://zestedesavoir.com/forums/sujet/12603/copier-coller-de-code-depuis-les-exports-pdf/)
Solution found on [here](https://tex.stackexchange.com/a/30793)

### CODE REVIEW

**Comment by Heziode** [comment]
It is nice !

The only thing I have to reproach is that it shifts the numbers.

Screenshot_line-numbers

**Comment by pierre-24** [comment]
Thus, maybe adding a `\hspace{.5em}` or something like that before `\small\textcolor ...` will do the trick ;)

**Comment by Situphen** [comment]
I added `%` at the end of the lines so that it doesn't shift the numbers, so we're good!

This solution doesn't work with the Firefox's PDF reader but works with Elementary OS's default PDF reader so I guess it depends if the PDF reader support the AccSup annotations.

**Comment by Heziode** [comment]
> This solution doesn't seem to work with Firefox's PDF reader but seems to work with Elementary OS's default PDF reader so I guess it depends if the PDF reader support the AccSup annotations.

Yep.

> Can you try with different PDF readers as well ?

Work for me with ungoogled-chromium and Okular on Archlinux.

**Comment by pierre-24** [comment]
Works for me on evince. And at least it is better than nothing :)

**Comment by artragis** [comment]
@sandhose can you deploy it please?

**Pull request merged**
