### PR TITLE
Add quotes (fix #2)

### LINKED ISSUE #2: Quote
There is already a [`quotation` environement](http://www.emerson.emory.edu/services/latex/latex_57.html) available in LaTeX, but without the possibility to set a source.

### PR DESCRIPTION
**Pull request by pierre-24**
Add a `Quote` environment.

### CODE REVIEW

**Comment by Karnaj** [comment]
Good. :)

But why `Quote` and not `Quotation`?

And we could have the source after "Citation" using the optional argument of QuoteBox.

```latex
\newenvironment{Quote}[1]{\begin{minipage}{\linewidth}\begin{QuoteBox}[#1]}
                         {\end{QuoteBox}\end{minipage}}
```

quote

**Comment by pierre-24** [comment]
> But why Quote and not Quotation?

Why not, indeed.

> And we could have the source after "Citation" using the optional argument of QuoteBox.

To mimic what is done on the website for the moment. But this is also good (`ntheorem` is a package that I didn't know before that).

Btw, I guess that the `minipage` prevent the block to be cut by a page break ?

**Comment by Karnaj** [comment]
> Btw, I guess that the minipage prevents the block to be cut by a page break ?

Yes it did.

> To mimic what is done on the website for the moment.

In that case, we can merge (unless you want to change the name of the environment).

**Comment by pierre-24** [comment]
Done.

**Pull request merged**
