### PR TITLE
Add Images macros

### PR DESCRIPTION
**Pull request by Karnaj**
This PR add two command two manage images easily (see #12). With these macros, we have a maximum size for the image.

### CODE REVIEW

**Comment by pierre-24** [comment]
Good to me :)

But due to the merge of #23, you'll need to rebase.

**Comment by Karnaj** [comment]
Done. 

I’d just discover we can resolve conflicts directly on Github.

**Comment by Karnaj** [comment]
[Error because of that](https://github.com/zestedesavoir/latex-template/blob/master/scripts/install_texlive.sh#L8L9). If texlive in the cache, we don’t install it and we don’t install `$EXTRA_PACKAGES`, even if there is a new package.

**Comment by Karnaj** [comment]
First fix travis fail.

**Comment by pierre-24** [comment]
Why did you close it ?

**Comment by Karnaj** [comment]
To first resolve travis issue (#35). I do it in #36 but the tests failed.  The problem is in install_texlive.sh.

**Pull request closed without merging**
