### PR TITLE
Add iframes (fix #11)

### LINKED ISSUE #11: The "iframes"
Right now, there is no equivalence for the videos and jsfidles (inserted by `!()` in zMD). Obviously, [and even if it is possible](https://tex.stackexchange.com/questions/1574/embedding-videos-and-animations), we would like to get a block reporting the url of the video instead of the video and a text message "to see the video, go to ...". 

Note that markdown does allow for caption on those iframes, so we should take this into account.

### PR DESCRIPTION
**Pull request by pierre-24**
Add support for iframes (`!(url)` in markdown), in a quite flexible manner (thanks to xparse).

@Karnaj : should I exchange the order of the arguments?

### CODE REVIEW

**Comment by Karnaj** [comment]
Good to me. What is the syntax in markdown to specify the iframe type?

**Comment by pierre-24** [comment]
There is no syntax to specify the type, but the parser makes the difference between video and jsfidle. So it is a possibility for the parser to make a difference (even though the default value works for most cases)

**Comment by Karnaj** [comment]
OK. Can be merged.

**Comment by pierre-24** [comment]
Let's do that :)

**Pull request merged**
