### PR TITLE
What if luatex85?

### PR DESCRIPTION
**Pull request by pierre-24**
Try to solve compatibility issues with `luatex85`.

### CODE REVIEW

**Comment by gustavi** [comment]
What is the problem ? How could I test it ?

**Comment by pierre-24** [comment]
> What is the problem ?

Well, the problem is LuaTeX and packaging: during the transition between LuaTeX 0.x and 1.x, the developers seems to have rewritten what we could call the PDF generation API with respect to LaTeX. Locally, I use a version of LuaTeX which is 1.04, and Travis use the last one (1.07 last time I checked). Problem, since @sandhose prefers (for good reasons) to rely on the Debian packages, zds uses LuaTeX 0.95, which generates errors.

This packages is supposed to fix the incompatibility issues. If I test the pdf generation with my version, it does not seems (visually) to affect the rendering, so for me that's good.

The question is: "does it works for zds?"

> How could I test it ?

Actually, I think one could try with a virtual machine and Debian Stretch ([testing and sid](https://www.tug.org/texlive/debian.html) ship the 2018 version of texlive, so probably the latest version of LuaTeX as well), which seems to be the version that zds is using, so:

+ Get debian stretch ;
+ Install [those packages](https://www.tug.org/texlive/debian.html) + `librsvg2-bin` and `imagemagick` (I don't know the exact names) ;
+ Clone the repository, `cd latex-template/tests/`, `make test` and then inspect the pdf files.

... Or use the latest version of texlive in the zds server, but that depends on @sandhose ;)

Personally, I'll try with a virtualbox on Sunday, I'm a bit busy before that ;)

**Comment by gustavi** [comment]
OK, I don't have a Debian 9 available now but I'll try next days. Don't hesitate to ping me next week if you have no news, bit busy too.

**Comment by pierre-24** [comment]
Ok, tested via Debian 9, it works <3

**Comment by artragis** [comment]
ok ping @sandhose can you update it on beta so that I make some tests?

**Pull request merged**
