### PR TITLE
Ping command.

### PR DESCRIPTION
**Pull request by Karnaj**
Adds a command `\ping`.

### CODE REVIEW

**Comment by pierre-24** [comment]
Shouldn't this command use the `website` variable ([defined here](https://github.com/zestedesavoir/latex-template/blob/ad1e23ae067b77d3e898e40f07920576266b78ca/zmdocument.cls#L502)). The answer actually depends how rebber renders it, though.

**Comment by pierre-24** [comment]
(by the way, don't forget to add it in [the documentation](https://github.com/zestedesavoir/latex-template/blob/master/documentation.md))

**Comment by Karnaj** [comment]
> Shouldn't this command use the `website` variable ([defined here](https://github.com/zestedesavoir/latex-template/blob/ad1e23ae067b77d3e898e40f07920576266b78ca/zmdocument.cls#L502)) ? The answer actually depends how rebber renders it, though.

Maybe `\ping{username}`?

```latex
\newcommand{\profileLink}[1]{\def\@profileLink{#1}}
\ifcsdef{@profileLink}{}{\profileLink{https://zestedesavoir.com/membres/voir/}}

\newcommand{\ping}[1]{\href{@profileLink/#1}{\textbf{@#1}}}
```

Then `Thanks to \ping{pierre\_24}` => "Thanks to **\@pierre_24**".

@artragis @TitiAlone ?

**Comment by artragis** [comment]
We do not parse ping in latex.

**Comment by pierre-24** [comment]
(I guess the idea is to add it)

**Comment by pierre-24** [comment]
(don't forget the documentation :'( )

**Comment by pierre-24** [comment]
Perfect :)

**Pull request merged**
