### PR TITLE
Fix/author: Cover author issue (fix #68) 

### LINKED ISSUE #68: Cover author issue
Some trouble on cover with author:

If pseudo is to long:

latex-template-cover_issue_pseudo-to-long

If tuto contains many authors:

latex-template-cover_issue_to-many-pseudo

Possible improvment: use lua for generating list of author. Not displaying too long pseudo and no more than 12 author. For other, add sentence like this: "et X autres auteurs"

### PR DESCRIPTION
**Pull request by Heziode**
This commit fix issue related to authors.
Display only 11 authors on cover and if there are more than,
it will display all authors on a new page between flyleaf and table of
contents.

This commit add:

- flyleaf: just after cover (blank page)
- Author page: diplay only if there is more than 11 authors

Note: lua script requiert [utf8.lua](https://github.com/Stepets/utf8.lua)

fix #68

### CODE REVIEW

**Comment by Heziode** [comment]
Need cach update…

**Comment by pierre-24** [comment]
Cache cleared, build restarted :)

**Comment by Heziode** [comment]
New clear needed…

**Comment by pierre-24** [comment]
Cleared and restarted. We should add a test so that the list of package is stored in the cache, and if the list differs, the cache is not used anyway ;)

**Comment by Heziode** [comment]
Hum… it's appear that travis does not clone subrepo…
Any idea to fix this ?

**Comment by pierre-24** [comment]
the subrepo?

**Comment by Heziode** [comment]
Lua code need [utf8-lua](https://github.com/Stepets/utf8.lua) for utf8 char suport.

**Comment by pierre-24** [comment]
Oh yeah. One of my question was "how am I suppose to get that file on my computer?". I think the answer to that question will guide the answer to your question :-°

**Comment by Heziode** [comment]
Hum… maybe with `--recursive`: `git clone --recursive my-amazing-repo`

**Comment by pierre-24** [comment]
Oh, that ! Ok, [something like this?](https://stackoverflow.com/a/24600210), maybe ?

**Comment by pierre-24** [comment]
Note that [according to the doc](https://docs.travis-ci.com/user/customizing-the-build/#Git-Submodules), Travis is supposed to fetch submodules o_O

**Comment by pierre-24** [comment]
How did you add the submodule, exactly?

**Comment by Heziode** [comment]
I've added the submodule just in clonning this repo at the root of latex-template repo.

**Comment by pierre-24** [comment]
That should be `git submodule add xxx`, [no ?](https://git-scm.com/book/en/v2/Git-Tools-Submodules) :)

**Comment by Heziode** [comment]
`"utf8.lua" already exists in the index`

I think `git clone` in git repo add automaticly subrepo.

**Comment by pierre-24** [comment]
agreed, but you are NOT supposed to do `git clone` for that in the first place ^^

**Comment by Heziode** [comment]
I meant that the first time I cloned it in the repo he automatically added it.

*Note: I've fixed path of utf8.lua module in lua script, bad path…*

**Comment by Heziode** [comment]
It is good :)

**Comment by pierre-24** [comment]
That works actually pretty well ;)

**Pull request merged**
