### PR TITLE
make errors fatal

### LINKED ISSUE #35: Travis should fail when tests fail
Failing tests aren't reported by travis because the Makefile ignores all errors.

Here's a build that should have failed: https://travis-ci.org/zestedesavoir/latex-template/builds/239482535

### PR DESCRIPTION
**Pull request by Karnaj**
Fix #35 making error fatals (thanks to @vhf).

### CODE REVIEW

**Comment by pierre-24** [comment]
So it is failing (because it miss the `glosaries` package). Then ... What ?

**Comment by Karnaj** [comment]
I tried to resolve it in #34. The error is "! LaTeX Error: File `glossaries.sty' not found." whereas [it’s in `EXTRA_PACKAGES`](https://github.com/zestedesavoir/latex-template/blob/master/scripts/install_texlive.sh#L6). In fact, these package were installed only if it texlive wasn’t installed. So, I add a line to install these package. But `tlmgr` was out to date.

 I will try again...

**Comment by pierre-24** [comment]
aaah, damn, its #33. When looking for the solution of that issue, the comment was usually "wait a few day, it will fix itself". The trouble is that the installation script is still expecting 2016 while some repository have still updated to 2017. And it is a pain in the ass --"

**Comment by pierre-24** [comment]
Well ... By any chance, @vhf, do you know how to destroy Travis cache ?

**Comment by vhf** [comment]
screen shot 2017-06-05 at 21 44 03

screen shot 2017-06-05 at 21 44 13

:)

**Comment by Karnaj** [comment]
And as you can see it, we have now another problem:"LaTeX Error: File \`mfirstuc.sty' not found".

**Comment by pierre-24** [comment]
Thanks @vhf :)

So, @Karnaj, I will delete the cache, you can add `mfirstuc` to the list of packages :)

**Comment by Karnaj** [comment]
I also delete longtable from the list (it’s in latex core)

**Comment by pierre-24** [comment]
```
=============================================================================
./install-tl-20170413/install-tl: The TeX Live versions of the local installation
and the repository being accessed are not compatible:
      local: 2016
 repository: 2017
Perhaps you need to use a different CTAN mirror?
(For more, see the output of install-tl --help, especially the
 -repository option.  Online via http://tug.org/texlive/doc.)
=============================================================================
```

Just go f\*\*\* yourself, texlive.

**Comment by pierre-24** [comment]
> TL17 was released on June 4. Please allow a couple of days for it to make its way around CTAN. 

So, [according to this page](http://tug.org/texlive/acquire-netinstall.html), we just have to ... Wait.

**Comment by Karnaj** [comment]
So, what to do ? Close the PR or wait to resolve the issue ?

**Comment by pierre-24** [comment]
What we can try is to cheat and use `ftp://tug.org/historic/systems/texlive/2017/install-tl-unx.tar.gz` on [that line](https://github.com/zestedesavoir/latex-template/blob/master/scripts/install_texlive.sh#L26), that should normally do the trick for one week or so.

**Comment by Karnaj** [comment]
Wait and see...

**Comment by pierre-24** [comment]
Well ... This is not good. Our profile seems wrong.

**Comment by Karnaj** [comment]
Why did we need this profile?

**Comment by pierre-24** [comment]
Basically, to trigger the installation of the small version instead of the full one, and the definition of the environment variable are also important. Otherwise, I doubt that most of the options does something interesting (for example the `w32_*` one). 

From what is not recognized any more, only `option_write18_restricted` is a bit annoying, since I think we want this on. So what we can try is to remove everything except the begining of the file (I say [those one](https://github.com/zestedesavoir/latex-template/blob/master/scripts/texlive.profile#L1-L15) + `portable 1`) and see what comes out.

**Comment by Karnaj** [comment]
[See that](https://www.tug.org/texlive/doc/install-tl.html#PROFILES). Some options have others names in TexLive 2017. I will try with the new names and if it doesn’t run i will remove everything.

**Comment by pierre-24** [comment]
So close :p (`in_place` is not recognized)

**Comment by pierre-24** [comment]
It works <3

Now it misses `xfor.sty`, but it did work :)

**Comment by pierre-24** [comment]
(sorry to put you trough all of that, btw :s )

**Comment by Karnaj** [comment]
And finally it runs. :) Such an assault course!

**Comment by pierre-24** [comment]
Waw, thanks you a lot!

**Pull request merged**
