### PR TITLE
Fix tabu.

### PR DESCRIPTION
**Pull request by Karnaj**
Download tabu package from https://github.com/tabu-issues-for-future-maintainer/tabu.

### CODE REVIEW

**Comment by pierre-24** [comment]
Very good idea :)

... But don't forget to also change the things on ZdS: developers will use [this scripts](https://github.com/zestedesavoir/zds-site/blob/dev/scripts/install_zds.sh), so you should probably add things [here](https://github.com/zestedesavoir/zds-site/blob/dev/scripts/install_zds.sh#L404), and I don't know exactly what to change for the infra of ZdS. Ping @artragis ?

**Comment by artragis** [comment]
about infra @Situphen will know best. 

As zds maintainer I just give green light on *functional* side.

**Comment by Situphen** [comment]
For the infra it's all good, I've got https://github.com/zestedesavoir/ansible-zestedesavoir/pull/16 ready!

**Comment by pierre-24** [comment]
If so, let's go :)

**Pull request merged**
