### PR TITLE
Allow to provide an alternative key for abbreviations

### LINKED ISSUE #106: Change the abbr command
As reported by @Karnaj, it is not possible to use a special character into `glossaries`. We therefore need a command which allow to provide a custom key. 

```latex
\documentclass{article}
\usepackage{glossaries}
 \newcommand{\abbr}[2]{\newglossaryentry{AT(et)BC}{name=#1, description={#2}}\gls{AT(et)BC}}
 
 \begin{document}
    \abbr{AT\&BC}{CC}
    \printglossaries
\end{document}
```

~~... To avoid breaking everything, we may need to provide a new command, then tell the guys on the zmarkdown side to use it instead :)~~ → No need for that if we use an optional parameter!

### PR DESCRIPTION
**Pull request by pierre-24**
fix #106

### CODE REVIEW

**Comment by artragis** [comment]
How can we use this in zmd? As far As I know we do not have "custom key" on markdown side. I think a good fix should be a LUA function that parses the key and deterministicaly changes special chars into customkey (for example &=>and)

**Comment by pierre-24** [comment]
Mmmh, not a bad I idea. I'll see if I can manage to do that :)

**Comment by artragis** [comment]
where are we there?

**Comment by pierre-24** [comment]
We are here, normally. I added the lua function so that `\abbrv{AT\&T}{American stuffs (...)}` works. You'll have nothing to do on the rebber side. Normally, I put all the special character for which I detected an issue.

(sorry for the long time, exams+vacations :sleeping: )

**Comment by pierre-24** [comment]
A few test later, I think we are good here :)

**Pull request merged**
