### PR TITLE
Don't use cache for minted

### PR DESCRIPTION
**Pull request by Karnaj**

### CODE REVIEW

**Comment by pierre-24** [comment]
Option clash ... `\setminted` ?

**Comment by Karnaj** [comment]
Fixed.

**Comment by Heziode** [comment]
Is there any reason to not use the cache ?
Because the cache is designed to speed up the compilation.

**Comment by pierre-24** [comment]
I don't know the exact reasons, but in the case of ZdS, a PDF is compiled once an for all, so the cache makes little sense. But I let @Karnaj justify its reasons ;)

**Comment by Heziode** [comment]
If this is the only reason, and even if this template is designed for ZdS, I think is a bad idea to "hardcode" the deactivation of the cache. Maybe a variable which can be set by the user is more relevant.

For example, I use this template has my `LoadClass` for my template for my university report. So I need to recompile many times my report, if this option is disabled, this will take a while (well, even more than usual) to (re)compile the report which contains many block of code.

**Comment by Karnaj** [comment]
It seems that the cache may cause some issues (probably cache issues when we got a PDF without the blocks of code). But you're right, an option is a better choice. @Heziode

**Comment by Karnaj** [comment]
I think we can merge now @pierre-24 @Heziode ?

**Comment by pierre-24** [comment]
Yes we can ;)

**Pull request merged**
